const HEIGHT_IN_BLOCKS = 20;
const WIDTH_IN_BLOCKS = 10;
const SCREEN_WIDTH = 640;
const SCREEN_HEIGHT = 480;
const BLOCK_SIZE = 22;
const EDGE_SIZE = 5;
const DROP_AREA_HEIGHT = 20 * 22; // HEIGHT_IN_BLOCKS * BLOCK_SIZE
const DROP_AREA_WIDTH = 10 * 22; // WIDTH_IN_BLOCKS * BLOCK_SIZE
const BORDER_X = 20;
const BORDER_Y = (480 - 20 * 22) / 2; // (SCREEN_HEIGHT - DROP_AREA_HEIGHT) / 2
const TEXT_AREA_X = 20 + 10 * 22; // BORDER_X + DROP_AREA_WIDTH

export { HEIGHT_IN_BLOCKS, WIDTH_IN_BLOCKS, SCREEN_WIDTH, SCREEN_HEIGHT, BLOCK_SIZE, EDGE_SIZE, DROP_AREA_HEIGHT, DROP_AREA_WIDTH, BORDER_X, BORDER_Y, TEXT_AREA_X };
